data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8000
    num_workers: 20
    wrap: false
    train:
      target: scdiff.data.denoising.DenoisingTrain
      params:
        dataset: HiresChr1
        fname: /public/home/hpc254701055/2_projects/10_schicdiff/1_scHiC/5_baseline/paperplots/6_caseData/2_callLoop_apa/inputData/6_hires_chr1/hires_20kb_chr1.h5ad
        post_cond_flag: true
        normalize: true
        return_raw: true
        splits:
          train: 0.8
          valid: 0.2
          test: 0
    validation:
      target: scdiff.data.denoising.DenoisingValidation
      params:
        dataset: HiresChr1
        fname: /public/home/hpc254701055/2_projects/10_schicdiff/1_scHiC/5_baseline/paperplots/6_caseData/2_callLoop_apa/inputData/6_hires_chr1/hires_20kb_chr1.h5ad
        post_cond_flag: true
        normalize: true
        return_raw: true
        splits:
          train: 0.8
          valid: 0.2
          test: 0
    test:
      target: scdiff.data.denoising.DenoisingTest
      params:
        dataset: HiresChr1
        fname: /public/home/hpc254701055/2_projects/10_schicdiff/1_scHiC/5_baseline/paperplots/6_caseData/2_callLoop_apa/inputData/6_hires_chr1/hires_20kb_chr1.h5ad
        post_cond_flag: true
        normalize: true
        return_raw: true
        splits:
          train: 0.8
          valid: 0.2
          test: 0
model:
  base_learning_rate: 1.0e-08
  target: scdiff.model.ScDiff
  params:
    inpaint: true
    save_path: /public/home/hpc254701055/2_projects/10_schicdiff/1_scHiC/5_baseline/7_scHiCDiff/6_caseStudy/2_hiresChr1-6567/results/full/eval_v2
    data_normalize: true
    return_raw: true
    t_sample_train_mode: indep
    mask_context: false
    mask_noised_context: false
    balance_loss: false
    loss_type: l2
    loss_strategy: recon_full
    parameterization: x0
    linear_start: 0.0001
    linear_end: 0.02
    log_every_t: 200
    timesteps: 1000
    input_key: input
    cond_key: cond
    cond_to_ignore: null
    monitor: val/loss_ema
    monitor_mode: min
    clip_denoised: true
    t_sample: 100
    recon_flag: true
    recon_sample: false
    denoise_flag: true
    denoise_t_sample: 1000
    classify_flag: false
    classifier_config:
      target: scdiff.modules.classifier.DiffusionClassifier
      params:
        query_mode: seen
        n_samples_list:
        - 5
        to_keep_list:
        - 1
        n_trials: 1
        loss: l2
        time_step_sampler: IterativeUniform
    model_config:
      target: scdiff.model.DiffusionModel
      params:
        no_time_embed: false
        save_path: /public/home/hpc254701055/2_projects/10_schicdiff/1_scHiC/5_baseline/7_scHiCDiff/6_caseStudy/2_hiresChr1-6567/results/full/eval_v2
        activation: gelu
        norm_layer: layernorm
        depth: 6
        dropout: 0.0
        embed_dim: 512
        dim_head: 64
        num_heads: 8
        decoder_embed_dim: 512
        decoder_dim_head: 64
        decoder_num_heads: 8
        mlp_time_embed: false
        cond_type: crossattn
        cond_emb_type: linear
        cond_cat_input: false
        cond_tokens: 1
        cond_mask_ratio: 0.1
        post_cond_layers: 1
        post_cond_norm: batchnorm
        post_cond_mask_ratio: 0.1
        mask_dec_cond: false
        mask_dec_cond_se: false
        mask_dec_cond_semlp: false
        mask_dec_cond_ratio: true
        mask_dec_cond_concat: false
        decoder_embed_type: embedder
        decoder_mask: inv_enc
        encoder_type: mlp
